MD003:        # heading-style
  style: atx
MD004:        # ul-style
  style: dash
MD009:        # no-trailing-spaces
  strict: true
MD013: false  # line-length
MD024: false  # no-duplicate-heading
MD029:        # ol-prefix
  style: ordered
MD033: false  # no-inline-html
MD035:        # hr-style
  style: ---
MD045: false  # no-alt-text
MD048:        # code-fence-style
  style: backtick
MD049:        # emphasis-style
  style: underscore
MD050:        # strong-style
  style: asterisk
