[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Boktai Speedrunning"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/shenef/Boktai-Speedrunning"
git-repository-icon = "fa-github"

additional-css = ["theme/pagetoc.css", "theme/css/colors.css", "theme/css/exp-table.css"]
additional-js = ["theme/pagetoc.js", "theme/js/any-percent-exp-table.js"]
# and theme/index.hbs by https://github.com/JorelAli/mdBook-pagetoc

[output.html.fold]
enable = true      # enable/disable section folding
level = 1          # when to start folding